1.4

diff --git a/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml b/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
--- a/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
+++ b/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
@@ -12,9 +12,13 @@ env:
   HOOK_METHOD: "vfs" # manual hook method,can choice vfs and normal.
   PROFILE_NAME: "olive_lineageos_a14.env" # your profile name.
   KERNELSU_SUS_PATCH: "false" # if u need manual susfs patch to kernelsu.
-  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
+  KPM_ENABLE: "false" # Only use it for SukiSU-Ultra.
+  KPM_PATCH_SOURCE: "" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .
+  GENERATE_DTB: "true" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
   GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.
   BUILD_DEBUGGER: "false" # Output build errors.
+  BUILD_OTHER_CONFIG: "false" # Merge config files.
+
 
 jobs:
   build:
@@ -56,8 +60,7 @@ jobs:
               BOOT_SOURCE
               LXC_ENABLE
               HAVE_NO_DTBO
-              GENERATE_DTB
-              GENERATE_CHIP
+              HAVE_NO_DTBO_TOOL
               ROM_TEXT
 
           )
@@ -102,24 +105,13 @@ jobs:
           remove-haskell: "true"
           remove-codeql: "true"
 
-      - name: Install GNU GCC
-        if: env.GCC_GNU == 'true'
-        run: |
-          if [ -z ${{ env.GCC_64_SOURCE }} ] && [ -z ${{ env.GCC_32_SOURCE }} ]; then
-            sudo apt-get install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi -y
-            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
-            echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
-          else
-            echo "You needn't gcc powered by system."
-          fi
-
       - name: Install necessary packages
         run: |
           lsb_release -a
-          UBUNTU_VERSION=$(lsb_release -sr)          
+          UBUNTU_VERSION=$(lsb_release -sr)
           sudo apt-get update
 
-          if [ $UBUNTU_VERSION == "22.04" ]; then
+          if [ $UBUNTU_VERSION == "22.04" ] || [ $UBUNTU_VERSION == "20.04" ]; then
             sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler
             sudo apt-get install p7zip p7zip-full -y
             if [ "${{ env.PYTHON_VERSION }}" == "3" ]; then
@@ -137,12 +129,27 @@ jobs:
             sudo apt-get install zstd libc6 binutils libc6-dev-i386 gcc g++ p7zip p7zip-full -y
           fi
 
+      - name: Install GNU GCC
+        if: env.GCC_GNU == 'true'
+        run: |
+          if [ -z ${{ env.GCC_64_SOURCE }} ] && [ -z ${{ env.GCC_32_SOURCE }} ]; then
+            sudo apt-get install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi -y
+            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
+            echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
+          else
+            echo "You needn't gcc powered by system."
+          fi
+
       - name: Set Compile Environment
         run: |
           cd $GITHUB_WORKSPACE
 
           # Set GCC Aarch64
-          if [ -z "${{ env.GCC_64_SOURCE }}" ]; then
+          if [ "${{ env.CLANG_SOURCE }}" == *proton* ]; then
+            echo "Detected Proton Clang. Not use GCC Source."
+            GCC_64_BIN=aarch64-linux-gnu-
+            echo "GCC_64=CROSS_COMPILE=$GCC_64_BIN" >> $GITHUB_ENV
+          elif [ -z "${{ env.GCC_64_SOURCE }}" ]; then
             echo "Not set GCC 64!"
           else
             if [[ "${{ env.GCC_64_SOURCE }}" == *".git" ]]; then
@@ -157,7 +164,7 @@ jobs:
               wget -O gcc-64.tar.xz ${{ env.GCC_64_SOURCE }}
               mkdir gcc-64            
               tar -C gcc-64/ -Jxvf gcc-64.tar.xz
-            fi
+            fi            
             if [[ "${{ env.GCC_64_SOURCE }}" == *'.zip' ]]; then
               wget -O gcc-64.zip ${{ env.GCC_64_SOURCE }}
               mkdir gcc-64
@@ -169,7 +176,11 @@ jobs:
 
 
           # Set GCC ARM32
-          if [ -z "${{ env.GCC_32_SOURCE }}" ]; then
+          if [ "${{ env.CLANG_SOURCE }}" == *proton* ]; then
+            echo "Detected Proton Clang. Not use GCC Source."
+            GCC_32_BIN=arm-linux-gnueabi-
+            echo "GCC_32=CROSS_COMPILE=$GCC_32_BIN" >> $GITHUB_ENV
+          elif [ -z "${{ env.GCC_32_SOURCE }}" ]; then
             echo "Not set GCC 32!"
           else
             if [[ "${{ env.GCC_32_SOURCE }}" == *".git" ]]; then
@@ -184,7 +195,7 @@ jobs:
               wget -O gcc-32.tar.xz ${{ env.GCC_32_SOURCE }}
               mkdir gcc-32            
               tar -C gcc-32/ -Jxvf gcc-32.tar.xz
-            fi
+            fi            
             if [[ "${{ env.GCC_32_SOURCE }}" == *'.zip' ]]; then
               wget -O gcc-32.zip ${{ env.GCC_32_SOURCE }}
               mkdir gcc-32
@@ -304,6 +315,20 @@ jobs:
           KSU_VERSION=$(cd ${{ env.KERNELSU_NAME }} && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
 
+          ## KPM Checker
+          if [[ -d "${{ env.KERNELSU_NAME }}/kernel/kpm" ]]; then
+            if [ -f "include/linux/set_memory.h" ] && [ "${{ env.KPM_ENABLE }}" == "true" ]; then
+                echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+                wget "${{ env.KPM_PATCH_SOURCE }}" -o patch
+                chmod a+x patch
+                echo "Set KPM successfully !"
+            elif [ "$KPM_ENABLE" == "true" ]; then
+                echo "Your kernel doesn't support KPM !"
+            else
+                echo "Doesn't enable KPM !"
+            fi
+          fi
+
           # Set SUSFS
           if [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
             if [[ "${{ env.SUSFS_FIXED }}" == true ]]; then
@@ -393,7 +418,7 @@ jobs:
           # sed -i 's/# CONFIG_SECCOMP is not set/CONFIG_SECCOMP=y/' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
 
       - name: Added mkdtboimg to kernel (Experiment)
-        if: env.HAVE_NO_DTBO == 'true'
+        if: env.HAVE_NO_DTBO == 'true' && env.HAVE_NO_DTBO_TOOL != 'true'
         run: |
           cd $GITHUB_WORKSPACE/device_kernel/scripts/dtc
           wget https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz
@@ -460,14 +485,6 @@ jobs:
             patch -p1 < 10_enable_susfs_for_ksu.patch || true
           fi
 
-      - name: Fixed Kernel Patch
-        if: env.SUSFS_ENABLE == 'true' && env.SUSFS_FIXED == 'true'
-        run: |
-          cd $GITHUB_WORKSPACE/device_kernel/
-          cp NonGKI_Kernel_Patches/4.19/ksu_hooks_sukisu_4.19.patch ./
-
-          patch -p1 < ksu_hooks_sukisu_4.19.patch || true
-
       - name: Patch Debugger
         if: env.BUILD_DEBUGGER == 'true'
         run: |
@@ -482,7 +499,15 @@ jobs:
                 echo "==========EOF=========="
             done
             false
-          fi      
+          fi
+
+      - name: Fixed Kernel Patch
+        if: env.SUSFS_ENABLE == 'true' && env.SUSFS_FIXED == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+          cp NonGKI_Kernel_Patches/4.19/ksu_hooks_sukisu_4.19.patch ./
+
+          patch -p1 < ksu_hooks_sukisu_4.19.patch || true
 
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
@@ -492,16 +517,115 @@ jobs:
 
       - name: Build Kernel
         run: |
+          MERGE_CONFIG_FILES=("vendor/debugfs.config" "vendor/lahaina_QGKI.config")
           export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH
           cd $GITHUB_WORKSPACE/device_kernel/
           make clean
           sudo apt-get install -y build-essential binutils-aarch64-linux-gnu
           if [ -z "${{ env.GCC_32 }}" ] && [ -z "${{ env.GCC_64 }}" ]; then
             make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.DEFCONFIG_NAME }}
+            if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
+                for FILES in "${MERGE_CONFIG_FILES[@]}"; do
+                    ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/arm64/configs/$FILES
+                done
+                make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} olddefconfig
+            fi
             make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }}
+          elif [ -z "${{ env.GCC_32 }}" ]; then
+            make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.DEFCONFIG_NAME }}
+            if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
+                for FILES in "${MERGE_CONFIG_FILES[@]}"; do
+                    ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/arm64/configs/$FILES
+                done
+                make O=out ARCH=arm64 ${{ env.GCC_64 }} olddefconfig
+            fi
+            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }}
+          elif [ -z "${{ env.CLANG_SOURCE }}" ]; then
+            make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.DEFCONFIG_NAME }}
+            if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
+                for FILES in "${MERGE_CONFIG_FILES[@]}"; do
+                    ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/arm64/configs/$FILES
+                done
+                make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} olddefconfig
+            fi
+            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }}
           else
             make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.DEFCONFIG_NAME }}
+            if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
+                for FILES in "${MERGE_CONFIG_FILES[@]}"; do
+                    ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/arm64/configs/$FILES
+                done
+                make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} olddefconfig
+            fi
             make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
+          fi
+
+          ## Generate DTBO
+          if [ "${{ env.HAVE_NO_DTBO }}" == "true" ] && [ "${{ env.HAVE_NO_DTBO_TOOL }}" == "true" ]; then
+            cd $GITHUB_WORKSPACE/device_kernel
+            mkdir dtbo_tool
+            cd dtbo_tool
+            wget https://android.googlesource.com/platform/system/libufdt/+archive/master/utils.tar.gz -o mkdtboimg.tar.gz
+            tar zxvf mkdtboimg.tar.gz
+            cd ../
+            if [ -d "$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/vendor" ]; then
+                python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtbo
+            else
+                python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/${{ env.GENERATE_CHIP }}/*.dtbo
+            fi
+          fi
+
+      - name: KPM Patcher (Experiment)
+        if: env.KPM_ENABLE == 'true'
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+          IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
+
+          if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
+            if [ -f "include/linux/set_memory.h" ]; then
+                    if [ -d "out/arch/arm64/boot/dts" ]; then
+                    rm -f $IMAGE_DIR/Image.gz-dtb
+                    rm -f $IMAGE_DIR/Image.gz
+                    cp patch $IMAGE_DIR/
+                    cd $IMAGE_DIR/
+                    ./patch
+                    rm -f Image
+                    mv oImage Image
+                    gzip -c Image > Image.gz
+                    cat Image.gz dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
+                    echo "Hook Image successfully !"
+                elif [ -d "out/arch/arm64/boot/vendor/dts" ]; then
+                    if [ -d "out/arch/arm64/boot/dts" ]; then
+                    rm -f $IMAGE_DIR/Image.gz-dtb
+                    rm -f $IMAGE_DIR/Image.gz
+                    cp patch $IMAGE_DIR/
+                    cd $IMAGE_DIR/
+                    ./patch
+                    rm -f Image
+                    mv oImage Image
+                    gzip -c Image > Image.gz
+                    cat Image.gz vendor/dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
+                    echo "Hook Image successfully !"
+                else
+                    echo "Not found dts folder, abort."
+                fi
+            else
+                echo "Not supported for your kernel !"
+            fi
+          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
+            rm -f $IMAGE_DIR/Image.gz
+            cp patch $IMAGE_DIR/
+            cd $IMAGE_DIR/
+            ./patch
+            rm -f Image
+            mv oImage Image
+            gzip -c Image > Image.gz
+            echo "Hook Image successfully !"
+          elif [[ -f "$IMAGE_DIR/Image" ]]; then
+            cp patch $IMAGE_DIR/
+            ./patch
+            mv oImage Image
+            echo "Hook Image successfully !"
           fi
 
       - name: Make Anykernel3 Flasher
@@ -530,9 +654,10 @@ jobs:
             cp -fp $IMAGE_DIR/Image.gz tmp
             echo "Found Image.gz !"
           elif [[ -f "$IMAGE_DIR/Image" ]]; then
-            gzip -c $IMAGE_DIR/Image > $IMAGE_DIR/Image.gz
-            cp -fp $IMAGE_DIR/Image.gz tmp
-            echo "Found Image ! Automatic convert Image.gz ! "
+            # gzip -c $IMAGE_DIR/Image > $IMAGE_DIR/Image.gz
+            # cp -fp $IMAGE_DIR/Image.gz tmp
+            cp -fp $IMAGE_DIR/Image tmp
+            echo "Found Image !"
           fi
 
           if [[ -f "$IMAGE_DIR/dtbo.img" ]]; then
@@ -593,6 +718,26 @@ jobs:
             rm -f out/kernel
             cp -fp $IMAGE_DIR/Image out/kernel
             echo "Found Image !"
+          fi
+
+          if [ -f "$IMAGE_DIR/dtb" ]; then
+            echo "Found DTB!"
+            cp -fp $IMAGE_DIR/dtb out/dtb
+          elif [ "${{ env.GENERATE_DTB }}" == "true" ]; then
+            if [ -d "$IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB out/dtb
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            elif [ -d "$IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB out/dtb
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            else
+                echo "Missing .dtb file in dts or dts/vendor ! Generate Failed !"
+                false
+            fi
+          else
+            echo "Doesn't found DTB! Your device maybe needn't the file."
           fi
 
           eval "mkboottools/mkbootimg.py $FORMAT_MKBOOTING -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img"
