new

diff --git a/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml b/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
--- a/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
+++ b/.github/workflows/build_kernel_redmi8_Lineages21_a14.yml
@@ -164,7 +164,7 @@ jobs:
               wget -O gcc-64.tar.xz ${{ env.GCC_64_SOURCE }}
               mkdir gcc-64            
               tar -C gcc-64/ -Jxvf gcc-64.tar.xz
-            fi            
+            fi
             if [[ "${{ env.GCC_64_SOURCE }}" == *'.zip' ]]; then
               wget -O gcc-64.zip ${{ env.GCC_64_SOURCE }}
               mkdir gcc-64
@@ -195,7 +195,7 @@ jobs:
               wget -O gcc-32.tar.xz ${{ env.GCC_32_SOURCE }}
               mkdir gcc-32            
               tar -C gcc-32/ -Jxvf gcc-32.tar.xz
-            fi            
+            fi
             if [[ "${{ env.GCC_32_SOURCE }}" == *'.zip' ]]; then
               wget -O gcc-32.zip ${{ env.GCC_32_SOURCE }}
               mkdir gcc-32
@@ -507,7 +507,7 @@ jobs:
                 echo "==========EOF=========="
             done
             false
-          fi          
+          fi
 
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
@@ -566,7 +566,7 @@ jobs:
             mkdir dtbo_tool
             cd dtbo_tool
             wget https://android.googlesource.com/platform/system/libufdt/+archive/master/utils.tar.gz -o mkdtboimg.tar.gz
-            tar -zxvf mkdtboimg.tar.gz
+            tar zxvf mkdtboimg.tar.gz
             cd ../
             if [ -d "$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/vendor" ]; then
                 python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtbo
@@ -582,51 +582,64 @@ jobs:
           IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
 
           if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
-            if [ -f "include/linux/set_memory.h" ]; then
-                    if [ -d "out/arch/arm64/boot/dts" ]; then
-                    rm -f $IMAGE_DIR/Image.gz-dtb
-                    rm -f $IMAGE_DIR/Image.gz
-                    cp patch $IMAGE_DIR/
-                    cd $IMAGE_DIR/
-                    ./patch
-                    rm -f Image
-                    mv oImage Image
-                    gzip -c Image > Image.gz
-                    cat Image.gz dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
-                    echo "Hook Image successfully !"
-                elif [ -d "out/arch/arm64/boot/vendor/dts" ]; then
-                    if [ -d "out/arch/arm64/boot/dts" ]; then
-                    rm -f $IMAGE_DIR/Image.gz-dtb
-                    rm -f $IMAGE_DIR/Image.gz
-                    cp patch $IMAGE_DIR/
-                    cd $IMAGE_DIR/
-                    ./patch
-                    rm -f Image
-                    mv oImage Image
-                    gzip -c Image > Image.gz
-                    cat Image.gz vendor/dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
-                    echo "Hook Image successfully !"
-                else
-                    echo "Not found dts folder, abort."
-                fi
-            else
-                echo "Not supported for your kernel !"
-            fi
+              MODE="gz-dtb"
           elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
-            rm -f $IMAGE_DIR/Image.gz
-            cp patch $IMAGE_DIR/
-            cd $IMAGE_DIR/
-            ./patch
-            rm -f Image
-            mv oImage Image
-            gzip -c Image > Image.gz
-            echo "Hook Image successfully !"
+              MODE="gz"
           elif [[ -f "$IMAGE_DIR/Image" ]]; then
-            cp patch $IMAGE_DIR/
-            ./patch
-            mv oImage Image
-            echo "Hook Image successfully !"
+              MODE="plain"
+          else
+              echo "No valid Image file found."
+              exit 1
           fi
+
+          case "$MODE" in
+            gz-dtb)
+              if [ -f "include/linux/set_memory.h" ]; then
+                  if [ -d "out/arch/arm64/boot/dts" ]; then
+                      rm -f "$IMAGE_DIR/Image.gz-dtb" "$IMAGE_DIR/Image.gz"
+                      cp patch "$IMAGE_DIR/"
+                      cd "$IMAGE_DIR/" || exit 1
+                      ./patch
+                      rm -f Image
+                      mv oImage Image
+                      gzip -c Image > Image.gz
+                      cat Image.gz dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
+                      echo "Hook Image successfully !"
+                  elif [ -d "out/arch/arm64/boot/vendor/dts" ]; then
+                      rm -f "$IMAGE_DIR/Image.gz-dtb" "$IMAGE_DIR/Image.gz"
+                      cp patch "$IMAGE_DIR/"
+                      cd "$IMAGE_DIR/" || exit 1
+                      ./patch
+                      rm -f Image
+                      mv oImage Image
+                      gzip -c Image > Image.gz
+                      cat Image.gz vendor/dts/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
+                      echo "Hook Image successfully !"
+                  else
+                      echo "Not found dts folder, abort."
+                  fi
+              else
+                  echo "Not supported for your kernel !"
+              fi
+              ;;
+            gz)
+              rm -f "$IMAGE_DIR/Image.gz"
+              cp patch "$IMAGE_DIR/"
+              cd "$IMAGE_DIR/" || exit 1
+              ./patch
+              rm -f Image
+              mv oImage Image
+              gzip -c Image > Image.gz
+              echo "Hook Image successfully !"
+              ;;
+            plain)
+              cp patch "$IMAGE_DIR/"
+              cd "$IMAGE_DIR/" || exit 1
+              ./patch
+              mv oImage Image
+              echo "Hook Image successfully !"
+              ;;
+          esac
 
       - name: Make Anykernel3 Flasher
         if: env.PACK_METHOD == 'Anykernel3'
