push

diff --git a/.github/workflows/build_kernel_s20_oneui5.1_a13.yml b/.github/workflows/build_kernel_s20_oneui5.1_a13.yml
--- a/.github/workflows/build_kernel_s20_oneui5.1_a13.yml
+++ b/.github/workflows/build_kernel_s20_oneui5.1_a13.yml
@@ -1,16 +1,7 @@
-name: Build Kernel Redmi8 (LineageOS 21) with KSU and SUSFS
+name: Build Kernel Samsung S20 5G (OneUI 5.1) (Snapdragon Only) with KSU and SUSFS
 on:
   workflow_call:
   workflow_dispatch:
-  push:
-env:
-  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
-  KERNELSU_METHOD: "shell" # shell, manual and only.
-  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
-  PATCHES_BRANCH: "op_kernel" # [your_branch] -> main
-  HOOK_METHOD: "vfs" # manual hook method,can choice vfs and normal.
-  PROFILE_NAME: "olive_lineageos_a14.env" # your profile name.
-  KERNELSU_SUS_PATCH: "true" # if u need manual susfs patch to kernelsu.
 
 jobs:
   build:
@@ -24,7 +15,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Prepare Configuration
         run: |
-          CONFIG_ENV=$(grep -w "CONFIG_ENV" Profiles/${{ env.PROFILE_NAME }} | head -n 1 | cut -d "=" -f 2)
+          CONFIG_ENV=$(grep -w "CONFIG_ENV" Profiles/x1q_oneui5.1_a13.env | head -n 1 | cut -d "=" -f 2)
           CONFIG_LIST=(
               DEVICE_NAME
               DEVICE_CODENAME
@@ -34,7 +25,6 @@ jobs:
               KERNEL_BRANCH
               CLANG_SOURCE
               CLANG_BRANCH
-              GCC_GNU
               GCC_64_SOURCE
               GCC_64_BRANCH
               GCC_32_SOURCE
@@ -50,7 +40,6 @@ jobs:
               AK3_BRANCH
               BOOT_SOURCE
               LXC_ENABLE
-              HAVE_NO_DTBO
               ROM_TEXT
 
           )
@@ -95,17 +84,6 @@ jobs:
           remove-haskell: "true"
           remove-codeql: "true"
 
-      - name: Install GNU GCC
-        if: env.GCC_GNU == 'true'
-        run: |
-          if [ -z ${{ env.GCC_64_SOURCE }} ] && [ -z ${{ env.GCC_32_SOURCE }} ]; then
-            sudo apt-get install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi -y
-            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
-            echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
-          else
-            echo "You needn't gcc powered by system."
-          fi
-
       - name: Install necessary packages
         run: |
           lsb_release -a
@@ -113,12 +91,20 @@ jobs:
           sudo apt-get update
 
           if [ $UBUNTU_VERSION == "22.04" ]; then
-            sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
+            sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3 dos2unix libncurses5
             sudo apt-get install p7zip p7zip-full -y
+            sudo ls -lah /usr/bin/ | grep "python"
           else
-            sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3
+            sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 dos2unix libncurses5
             sudo apt-get install zstd libc6 binutils libc6-dev-i386 gcc g++ p7zip p7zip-full -y
+            sudo ls -lah /usr/bin/ | grep "python"
           fi
+
+      - name: Install GNU GCC
+        run: |
+          sudo apt-get install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi -y
+          echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
+          echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
 
       - name: Set Compile Environment
         run: |
@@ -222,28 +208,24 @@ jobs:
             echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
             echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
           fi
-          if [[ ${{ env.LXC_ENABLE }} == "true" ]]; then
-           echo "CONFIG_VIRTUALIZATION=y" >> android-kernel/arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
-           echo "CONFIG_KVM=y" >> android-kernel/arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
-           echo "CONFIG_VHOST_NET=y" >> android-kernel/arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
-           echo "CONFIG_VHOST_CROSS_ENDIAN_LEGACY=y" >> android-kernel/arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
-          fi
 
       - name: Set Pack Method and KernelSU and SUSFS
         run: |
           # Variable
           SUSFS_SOURCE=https://gitlab.com/simonpunk/susfs4ksu.git
           SUSFS_BRANCH=kernel-${{ env.KERNEL_VERSION }}
+          PACK_METHOD=MKBOOTIMG # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
+          KERNELSU_METHOD=shell # shell and manual
 
-          # Set ${{ env.PACK_METHOD }} and KernelSU
-          if [[ ${{ env.PACK_METHOD }} == "Anykernel3" ]]; then
+          # Set $PACK_METHOD and KernelSU
+          if [[ $PACK_METHOD == "Anykernel3" ]]; then
             cd $GITHUB_WORKSPACE/device_kernel
             if [[ -d "Anykernel3" ]]; then
               echo "Found Anykernel3 in Kernel!"
             else
               git clone ${{ env.AK3_SOURCE }} -b ${{ env.AK3_BRANCH }} Anykernel3 --depth=1
             fi
-          elif [[ ${{ env.PACK_METHOD }} == "MKBOOTIMG" ]]; then
+          elif [[ $PACK_METHOD == "MKBOOTIMG" ]]; then
             cd $GITHUB_WORKSPACE
             git clone https://android.googlesource.com/platform/system/tools/mkbootimg $GITHUB_WORKSPACE/mkboottools -b main-kernel-build-2024 --depth=1
             wget ${{ env.BOOT_SOURCE }} -O $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
@@ -251,40 +233,30 @@ jobs:
           else
             exit
           fi
-          echo "PACK_METHOD=${{ env.PACK_METHOD }}" >> $GITHUB_ENV
+          echo "PACK_METHOD=$PACK_METHOD" >> $GITHUB_ENV
 
-          if [[ ${{ env.KERNELSU_METHOD }} == "shell" ]]; then
+          if [[ $KERNELSU_METHOD == "shell" ]]; then
             curl -sSL ${{ env.KERNELSU_SOURCE }} | bash -s ${{ env.KERNELSU_BRANCH }}
-          elif [[ ${{ env.KERNELSU_METHOD }} == "manual" ]]; then
+          elif [[ $KERNELSU_METHOD == "manual" ]]; then
             rm -rf KernelSU && rm -rf KernelSU-Next
             git clone ${{ env.KERNELSU_SOURCE }} -b ${{ env.KERNELSU_BRANCH }} ${{ env.KERNELSU_NAME }}
             ln -sf "$(realpath --relative-to="$KERNEL_LOCATION/drivers" "$KERNEL_LOCATION/KernelSU-Next/kernel")" "kernelsu"
             grep -q "kernelsu" "$KERNEL_LOCATION/drivers/Makefile" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> $KERNEL_LOCATION/drivers/Makefile
             grep -q "source \"drivers/kernelsu/Kconfig\"" "$KERNEL_LOCATION/drivers/Kconfig" || sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" "$KERNEL_LOCATION/drivers/Kconfig"
             echo "KernelSU Settings done."
-          elif [[ ${{ env.KERNELSU_METHOD }} == "only" ]];then
-            rm -rf KernelSU && rm -rf KernelSU-Next
-            git clone ${{ env.KERNELSU_SOURCE }} -b ${{ env.KERNELSU_BRANCH }} ${{ env.KERNELSU_NAME }}
-            echo "KernelSU git done."
           else
             exit
           fi
-          echo "KERNELSU_METHOD=${{ env.KERNELSU_METHOD }}" >> $GITHUB_ENV
+          echo "KERNELSU_METHOD=$KERNELSU_METHOD" >> $GITHUB_ENV
           KSU_VERSION=$(cd ${{ env.KERNELSU_NAME }} && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
 
           # Set SUSFS
           if [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
             if [[ "${{ env.SUSFS_FIXED }}" == true ]]; then
-              if [ -z "${{ env.PATCHES_SOURCE }}" ] || [ -z "${{ env.PATCHES_BRANCH }}" ]; then
-                echo "Please input vaild source and branch!"
-                exit
-              elif [[ ${{ env.PATCHES_SOURCE }} == *".git" ]]; then
-                echo "Please do not set a full URL in PATCH_SOURCE!"
-                false
-              else
-                git clone https://github.com/${{ env.PATCHES_SOURCE }}.git -b ${{ env.PATCHES_BRANCH }} NonGKI_Kernel_Patches --depth=1 # It's not necessary.
-              fi
+              PATCHES_SOURCE=JackA1ltman/NonGKI_Kernel_Patches
+              PATCHES_BRANCH=op_kernel
+              git clone https://github.com/$PATCHES_SOURCE.git -b $PATCHES_BRANCH NonGKI_Kernel_Patches --depth=1 # It's not necessary.
             fi
             git clone $SUSFS_SOURCE -b $SUSFS_BRANCH susfs4ksu --depth=1
             cp susfs4ksu/kernel_patches/fs/* fs/
@@ -298,79 +270,49 @@ jobs:
           cd $GITHUB_WORKSPACE
           KERNEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $1}')
           PATCHLEVEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $2}')
-          if grep -q "CONFIG_KSU" "device_kernel/fs/exec.c"; then
-            echo "Your kernel source code appears to have been manually patched, so this step is skipped."
-          else
-            if [[ ${{ env.HOOK_METHOD }} == "normal" ]]; then
-              if [[ -f "/tmp/Patches/normal_patches.sh" ]]; then
-                  cp /tmp/Patches/normal_patches.sh device_kernel/
-                  cd device_kernel
-                  bash normal_patches.sh
-                  echo "execuated patch successfully."
-                  if [ $KERNEL -lt 5 ] && [ $PATCHLEVEL -lt 14 ]; then
-                      cp /tmp/Patches/extra_patches.sh device_kernel/
-                      cd device_kernel
-                      bash extra_patches.sh
-                      echo "execuated extra patch successfully."
-                  else
-                      echo "your kernel needn't the patch."
-                  fi
-              else
-                  echo "Cannot found normal_patches.sh in build project , please check u file existed in build project !"
-                  exit
-              fi
-            elif [[ ${{ env.HOOK_METHOD }} == "vfs" ]]; then
-              if [[ -f "/tmp/Patches/vfs_hook_patches.sh" ]]; then
-                  cp /tmp/Patches/vfs_hook_patches.sh device_kernel/
-                  cd device_kernel
-                  bash vfs_hook_patches.sh
-                  echo "execuated vfs patch successfully."
-                  if [ $KERNEL -lt 5 ] && [ $PATCHLEVEL -lt 14 ]; then
-                      cp /tmp/Patches/extra_patches.sh device_kernel/
-                      cd device_kernel
-                      bash extra_patches.sh
-                      echo "execuated extra patch successfully."
-                  else
-                      echo "your kernel needn't extra patch."
-                  fi
-              else
-                  echo "Cannot found vfs_hook_patches.sh in build project , please check u file existed in build project !"
-                  exit
-              fi
+
+          if [[ -f "/tmp/Patches/normal_patches.sh" ]]; then
+            cp /tmp/Patches/normal_patches.sh device_kernel/
+            cd device_kernel
+            bash normal_patches.sh
+            if [ $KERNEL -lt 5 ] && [ $PATCHLEVEL -lt 14 ]; then
+                cp /tmp/Patches/extra_patches.sh device_kernel/
+                cd device_kernel
+                bash extra_patches.sh
             else
-              echo "please input vaild option!"
-              exit
+                echo "your kernel needn't the patch."
             fi
+            if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
+                cp /tmp/Patches/backport_patches.sh ./
+                bash backport_patches.sh
+                echo "execuated backport patch successfully."
+            fi
+          else
+            echo "Cannot found normal_patches.sh in build project , please check u file existed in build project !"
           fi
 
       - name: Extra Kernel Options
         run: |
           # Only ${{ env.DEVICE_NAME }} use it.
           cd $GITHUB_WORKSPACE/device_kernel
-          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_LTO_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_SHADOW_CALL_STACK=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_RELR=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          echo "CONFIG_KASAN_STACK_ENABLE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          sed -i 's/# CONFIG_SECCOMP is not set/CONFIG_SECCOMP=y/' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          find ./ -name Kconfig -exec dos2unix {} \;
+          sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/g' scripts/dtc/dtc-lexer.l
+          sed -i 's/static union __packed gsi_channel_scratch/static union gsi_channel_scratch/g' drivers/platform/msm/gsi/gsi.c
+          sed -i 's/CONFIG_UH=y/# CONFIG_UH is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_UH_RKP=y/# CONFIG_UH_RKP is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_KDP_CRED=y/# CONFIG_KDP_CRED is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_KDP_NS=y/# CONFIG_KDP_NS is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_KDP_DMAP=y/# CONFIG_KDP_DMAP is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_UH_LKM_BLOCK=y/# CONFIG_UH_LKM_BLOCK is not set/g' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's|$(srctree)/toolchain/qcom_llvm/10.0/bin/clang|$(srctree)/../clang-custom/bin/clang|g' ./Makefile
+          sed -i 's|$(srctree)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9|$(srctree)/../gcc-64|g' ./Makefile
+          sudo rm /usr/bin/python
+          sudo ln -s /usr/bin/python2.7 /usr/bin/python
+          python --version
+          echo "check python version: if python version is 3,this build will fail at last."
+          export KERNEL_LLVM_BIN=$GITHUB_WORKSPACE/clang-custom/bin/clang
 
-      - name: Added mkdtboimg to kernel (Experiment)
-        if: env.HAVE_NO_DTBO == 'true'
-        run: |
-          cd $GITHUB_WORKSPACE/device_kernel/scripts/dtc
-          wget https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz
-          tar zxvf src.tar.gz
-          rm -f src.tar.gz
-
-          cd $GITHUB_WORKSPACE/device_kernel
-          cp /tmp/Patches/temp_dtbo.patch ./
-          patch -p1 < temp_dtbo.patch
-          sed -i '/targets := Image Image.bz2 Image.gz Image.lz4 Image.lzma Image.lzo/s/$/ dtbo.img/' ./arch/arm64/boot/Makefile
-          sed -i '/$(obj)\/Image\.gz-dtb: $(obj)\/Image\.gz $(DTB_OBJS) FORCE/a \#DTBO\n$(obj)\/dtbo.img: $(DTBO_OBJS) FORCE\n\t$(call if_changed,mkdtimg)' ./arch/arm64/boot/Makefile
-          sed -i '/KBUILD_DTBS\t:= dtbs/a \#DTBO\nKBUILD_DTBO_IMG := dtbo.img' ./arch/arm64/Makefile
-          sed -i '/dtc-tmp = $(subst $(comma),_,$(dot-target)\.dts\.tmp)/a \#DTBO\n# mkdtimg\n#----------------------------------------------------------------------------\nquiet_cmd_mkdtimg = DTBOIMG $@\ncmd_mkdtimg = python3 $(srctree)\/scripts\/dtc\/mkdtboimg.py create $@ --page_size=4096 $(filter-out FORCE,$^)' ./scripts/Makefile.lib
-
-      - name: Setup LXC (Experiment)
+      - name: Setup LXC
         if: env.LXC_ENABLE == 'true'
         run: |
           cd $GITHUB_WORKSPACE/device_kernel
@@ -428,12 +370,12 @@ jobs:
           cd $GITHUB_WORKSPACE/device_kernel/
           cp NonGKI_Kernel_Patches/kona_oos/namespace_fixed.patch ./
           cp NonGKI_Kernel_Patches/kona_oos/task_mmu_fixed.patch ./
-          cp NonGKI_Kernel_Patches/kona_oos/ksu_backport.patch ./           
-                    
+          cp NonGKI_Kernel_Patches/kona_oos/ksu_backport.patch ./
+
           patch -p1 < namespace_fixed.patch || true
           patch -p1 < task_mmu_fixed.patch || true
-          patch -p1 < ksu_backport.patch || true       
-                             
+          patch -p1 < ksu_backport.patch || true
+
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
         with:
